version: "3.7"

networks:
  proxy:
    driver: ${COMPOSE_NETWORK_DRIVER?}
    external: ${COMPOSE_NETWORK_EXTERNAL?}
  secure:
    driver: ${COMPOSE_NETWORK_DRIVER?}
    external: ${COMPOSE_NETWORK_EXTERNAL?}

services:
  traefik:
    volumes:
      - ../../.data/traefik/ssl/:/etc/traefik/ssl/
      - ../../.logs/traefik/:/var/log/traefik/
    ports:
      - "${TRAEFIK_HOST_HTTP_PORT:-80}:80"
      - "${TRAEFIK_HOST_HTTPS_PORT:-443}:443"
    networks:
      - proxy
      - secure
    restart: unless-stopped
    depends_on:
      - dockersocket

  dockersocket:
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - POST=0
      - INFO=1
      - IMAGES=1
      - NODES=1
      - VOLUMES=1
      - NETWORKS=1
      - EXEC=1
    privileged: true
    networks:
      - secure

  logger:
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ../../.logs/traefik:/var/log/traefik
    networks:
      - secure
    depends_on:
      - traefik

  # portainer:
  #   image: portainer/portainer-ce:latest
  #   restart: unless-stopped
  #   security_opt:
  #     - no-new-privileges:true
  #   networks:
  #     - secure
  #     - proxy
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - ../../.data/portainer:/data
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.portainer.entrypoints=https
  #     - traefik.http.routers.portainer.rule=Host(`portainer.${TRAEFIK_DOMAIN_NAME}`)
  #     - traefik.http.services.portainer.loadbalancer.server.port=9000
  #   depends_on:
  #     - dockersocket
  #     - traefik
