version: "3.7"

services:
  traefik:
    image: ${DOCKER_REGISTRY?}/${DOCKER_NAMESPACE?}/traefik-${ENV?}:${TAG?}
    build:
      context: ../
      dockerfile: ./images/traefik/Dockerfile
      target: ${ENV?}
      args:
        - TIMEZONE=${TIMEZONE?}
        - TRAEFIK_VERSION=${TRAEFIK_VERSION?}
        - TRAEFIK_LOG_LEVEL=${TRAEFIK_LOG_LEVEL?}
        - TRAEFIK_API_DASHBOARD=${TRAEFIK_API_DASHBOARD?}
        - TRAEFIK_API_INSECURE=${TRAEFIK_API_INSECURE?}
        - TRAEFIK_DOMAIN_NAME=${TRAEFIK_DOMAIN_NAME?}
        - TRAEFIK_DOCKER_NETWORK=${TRAEFIK_DOCKER_NETWORK?}
        - TRAEFIK_DOCKER_ENTRYPOINT=${TRAEFIK_DOCKER_ENTRYPOINT?}
        - TRAEFIK_ACME_EMAIL_ADDRESS=${TRAEFIK_ACME_EMAIL_ADDRESS?}
        - TRAEFIK_ACME_DNS_CHALLENGE_PROVIDER=${TRAEFIK_ACME_DNS_CHALLENGE_PROVIDER?}
        - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN?}
        - TRAEFIK_BASIC_AUTH_USERNAME=${TRAEFIK_BASIC_AUTH_USERNAME}
        - TRAEFIK_BASIC_AUTH_PASSWORD_HASH=${TRAEFIK_BASIC_AUTH_PASSWORD_HASH}

  dockersocket:
    image: ${DOCKER_REGISTRY?}/${DOCKER_NAMESPACE?}/docker-socket-proxy-${ENV?}:${TAG?}
    build:
      context: ../
      dockerfile: ./images/docker-socket-proxy/Dockerfile
      target: ${ENV?}
      args:
        - SOCKET_PROXY_VERSION=${SOCKET_PROXY_VERSION?}

  logger:
    image: ${DOCKER_REGISTRY?}/${DOCKER_NAMESPACE?}/logger-${ENV?}:${TAG?}
    build:
      context: ../
      dockerfile: ./images/logger/Dockerfile
      target: ${ENV?}
      args:
        - ALPINE_VERSION=${ALPINE_VERSION?}
        - TIMEZONE=${TIMEZONE?}
