version: "3.7"

networks:
  proxy:
    driver: ${COMPOSE_NETWORK_DRIVER?}
    external: ${COMPOSE_NETWORK_EXTERNAL?}
  secure:
    driver: ${COMPOSE_NETWORK_DRIVER?}
    external: ${COMPOSE_NETWORK_EXTERNAL?}

services:
  traefik:
    volumes:
      - ../../.data/traefik/ssl/:/etc/traefik/ssl/
      - ../../.logs/traefik/:/var/log/traefik/
    ports:
      - "${TRAEFIK_HOST_HTTP_PORT:-80}:80"
      - "${TRAEFIK_HOST_HTTPS_PORT:-443}:443"
    networks:
      - proxy
      - secure
    restart: unless-stopped
    depends_on:
      - dockersocket

  dockersocket:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - POST=0
      - INFO=1
      - IMAGES=1
      - NODES=1
      - VOLUMES=1
      - NETWORKS=1
      - EXEC=1
    privileged: true
    networks:
      - secure
    restart: unless-stopped

  logger:
    volumes:
      - ../../.logs/traefik:/var/log/traefik
    networks:
      - secure
    depends_on:
      - traefik
