# http:
#   routers:
#     custom:
#       rule: Host(`custom.example.com`)
#       service: custom
#       tls:
#         certresolver: letsEncrypt

#   services:
#     custom:
#       loadBalancer:
#         servers:
#           - url: http://192.168.1.1:8080
