http:
  middlewares:
    # A basic authentification middleware, to protect the Traefik dashboard to anyone except myself
    # Use with traefik.http.routers.myRouter.middlewares: "traefikBasicAuth@file"
    traefikBasicAuth:
      basicAuth:
        users:
          - "__TRAEFIK_BASIC_AUTH_USERNAME:__TRAEFIK_BASIC_AUTH_PASSWORD_HASH"

    # Recommended default middleware for most of the services
    # Use with traefik.http.routers.myRouter.middlewares: "default@file"
    # Equivalent of traefik.http.routers.myRouter.middlewares: "securityHeaders@file,gzip@file"
    default:
      chain:
        middlewares:
          - securityHeaders
          - corsHeaders
          - cacheHeaders
          - gzip

    securityHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          server: ""
          X-Forwarded-Proto: "https"
        sslProxyHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: "same-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
        frameDeny: true
        sslForceHost: true
        permissionsPolicy: "geolocation=(self), microphone=(), camera=(), payment=(), usb=(), vr=(), fullscreen=*"

    corsHeaders:
      headers:
        accessControlAllowCredentials: true
        accessControlAllowHeaders:
          - Origin
          - Authorization
          - Content-Type
        accessControlAllowMethods:
          - OPTION
          - GET
          - POST
          - PUT
          - PATCH
        accessControlAllowOriginList: "__TRAEFIK_CORS_ALLOW_ORIGIN"
        accessControlMaxAge: 100
        addVaryHeader: true

    cacheHeaders:
      headers:
        customResponseHeaders:
          Cache-Control: "no-cache, max-age=0"

    gzip:
      compress: {}
